<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
        }
        th {
            background-color: #2196F3;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 10px;
            color: #666;
        }
        .summary {
            margin-top: 20px;
            padding: 10px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
        }
        .order-details {
            font-size: 9px;
            margin-left: 20px;
            margin-top: 5px;
        }
        .order-details table {
            margin-top: 5px;
            font-size: 9px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Generated on: {{ $date }}</p>
        <p>Total Records: {{ $orders->count() }}</p>
        <p>Total Amount: ${{ number_format($orders->sum('total_price'), 2) }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Customer</th>
                <th>Order Date</th>
                <th>Total Price</th>
                <th>Items</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($orders as $order)
                <tr>
                    <td>{{ $order->id }}</td>
                    <td>
                        <strong>{{ $order->customer->username ?? 'N/A' }}</strong><br>
                        <small>{{ $order->customer->email ?? 'N/A' }}</small>
                    </td>
                    <td>{{ $order->order_date->format('Y-m-d H:i:s') }}</td>
                    <td>${{ number_format($order->total_price, 2) }}</td>
                    <td>
                        @if($order->orderDetails && $order->orderDetails->count() > 0)
                            <div class="order-details">
                                @foreach($order->orderDetails as $detail)
                                    • {{ $detail->product->title ?? 'N/A' }} 
                                    (Qty: {{ $detail->quantity }}, 
                                    Price: ${{ number_format($detail->unit_price, 2) }})<br>
                                @endforeach
                            </div>
                        @else
                            No items
                        @endif
                    </td>
                    <td>{{ $order->created_at->format('Y-m-d H:i:s') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center;">No orders found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        <strong>Summary:</strong><br>
        Total Orders: {{ $orders->count() }}<br>
        Total Revenue: ${{ number_format($orders->sum('total_price'), 2) }}<br>
        Average Order Value: ${{ $orders->count() > 0 ? number_format($orders->avg('total_price'), 2) : '0.00' }}
    </div>

    <div class="footer">
        <p>Page generated by Laravel Export System</p>
    </div>
</body>
</html>

